"""added foreign key user_uid in book model

Revision ID: 728706004aca
Revises: 9c0024b37506
Create Date: 2026-04-21 13:40:41.776830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '728706004aca'
down_revision: Union[str, Sequence[str], None] = '9c0024b37506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('users', 'id')
    op.add_column('books', sa.Column('user_uid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'uid')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
